services:
  name_pending:
    container_name: name_pending
    image: name_pending
    mem_limit: 1g
    cpus: "2.0"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6969:6969"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "nc", "-z", "-w", "3", "127.0.0.1", "6969"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
